services:
  app:
    user: "${UID}:${GID}"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "8000:3000"
    command: sh -c "yarn dev"
