version: "3"

tasks:
  showcase:
    dir: NeoShowcase
    cmds:
      - make init && make up
    desc: "Default task"

  down-showcase:
    dir: NeoShowcase
    cmds:
      - make down
    desc: "Build the project"

  traq:
    dir: traQ
    cmds:
      - make up
    desc: "Run tests"

  lint:
    cmds:
      - docker compose run -it app yarn lint
    desc: "Lint the project"

  format:
    cmds:
      - docker compose run -it app yarn format
    desc: "Format the project"
  format-and-lint:
    deps:
      - format
      - lint
    desc: "Format and lint the project"
